name: lovelymachine
favicon: null
layout_spectrum: 0.7758005706127733
typography_spectrum: 0.1785108505282551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.897746225586161
  lightness: 0.37230812245979905
  saturation: 0.2734902175143361
  rhythmicContrast: 0.46371984924189746
purpose: []
